### ISSUE TITLE
'/home/darth/Projects/matlab/emnist-letters.mat' file does not exist

### ISSUE THREAD

**Issue by benldrmn** [AFAgarap/dl-relu#10]
Hi,

in emnist-letters-lenet.py, there's the line:
data = loadmat('/home/darth/Projects/matlab/emnist-letters.mat')
which seem to refer to some matrix stored locally on your private machine. Is it possible to add this matrix to assets?
Also, a brief explanation of the purpose of the code in this file would be great.

Thanks!
Ben

**Comment by AFAgarap** [comment]
Hi Ben,

I'm currently working on updating this repository.

Kindly wait for my updates later.

Best regards,
Abien
